
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OBJDICT_H
#define OBJDICT_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 UAECAB_valueRangeTest (UNS8 typeValue, void * value);
const indextable * UAECAB_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data UAECAB_Data;
extern UNS8 RX[8];		/* Mapped at index 0x2000, subindex 0x01 - 0x08 */
extern UNS8 TX[2];		/* Mapped at index 0x2200, subindex 0x01 - 0x02 */

#endif // OBJDICT_H
